# src/report.py

import os
import io
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer,
    Table, TableStyle, HRFlowable
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from groq import Groq
from dotenv import load_dotenv

load_dotenv()


# ══════════════════════════════════════════════════════════════════════════
#  GENERATE AI REPORT CONTENT VIA GROQ
# ══════════════════════════════════════════════════════════════════════════

def generate_report_content(
    result      : dict,
    stock_label : str,
    sentiment   : dict = None
) -> dict:
    """
    Use Groq LLaMA to generate full professional
    trading report content.
    """

    api_key = os.getenv("GROQ_API_KEY")

    if not api_key:
        return {"error": "⚠️ Groq API key not found!"}

    # ── Build Context ─────────────────────────────────────────────
    sentiment_text = ""
    if sentiment:
        sentiment_text = f"""
News Sentiment Analysis:
- Overall Sentiment : {sentiment.get('sentiment', 'N/A')}
- Sentiment Score   : {sentiment.get('score', 50)}/100
"""

    prompt = f"""
Generate a professional stock analysis report for {stock_label}.

## Data:
- Stock          : {stock_label}
- Prediction     : {result.get('prediction', 'N/A')}
- Confidence     : {result.get('confidence', 0)}%
- Model Accuracy : {result.get('accuracy', 0)}%
- Close Price    : ${result.get('latest_close', 0)}
- RSI (14)       : {result.get('latest_rsi', 0)}
- MACD           : {result.get('latest_macd', 0)}
- MA7            : {result.get('latest_ma7', 0)}
- MA21           : {result.get('latest_ma21', 0)}
- Top Features   : {result.get('top_features', [])}
{sentiment_text}
- Report Date    : {datetime.now().strftime('%B %d, %Y')}

Generate these sections clearly:

EXECUTIVE_SUMMARY:
Write 3-4 sentences summarizing the overall analysis.

TECHNICAL_ANALYSIS:
Write detailed technical analysis covering RSI, MACD,
Moving Averages and what they indicate. 4-5 sentences.

PREDICTION_ANALYSIS:
Explain the ML prediction in detail. Why BULLISH or BEARISH?
What indicators drove the decision? 4-5 sentences.

SENTIMENT_ANALYSIS:
Analyze overall market sentiment based on technical data
and news if available. 3-4 sentences.

RISK_ASSESSMENT:
List 4 key risk factors as bullet points starting with "-"

TRADING_RECOMMENDATION:
Give overall trading recommendation in 3-4 sentences.
Always include risk warning.

DISCLAIMER:
This report is generated by AI for educational and
simulation purposes only. Not financial advice.

Keep each section professional, clear and concise.
Separate sections with the exact labels shown above.
"""

    try:
        client = Groq(api_key=api_key)

        response = client.chat.completions.create(
            messages=[
                {
                    "role"   : "system",
                    "content": (
                        "You are a professional financial analyst "
                        "generating formal stock market reports. "
                        "Write in a clear, professional tone. "
                        "Always include risk disclaimers."
                    )
                },
                {
                    "role"   : "user",
                    "content": prompt
                }
            ],
            model       = "llama-3.3-70b-versatile",
            temperature = 0.4,
            max_tokens  = 1500,
        )

        content = response.choices[0].message.content

        # ── Parse Sections ────────────────────────────────────────
        sections = {}
        current_section = None
        current_text    = []

        section_keys = [
            "EXECUTIVE_SUMMARY", "TECHNICAL_ANALYSIS",
            "PREDICTION_ANALYSIS", "SENTIMENT_ANALYSIS",
            "RISK_ASSESSMENT", "TRADING_RECOMMENDATION",
            "DISCLAIMER"
        ]

        for line in content.split("\n"):
            line = line.strip()
            found_section = False
            for key in section_keys:
                if key in line.upper():
                    if current_section:
                        sections[current_section] = " ".join(current_text).strip()
                    current_section = key
                    current_text    = []
                    found_section   = True
                    break
            if not found_section and current_section:
                if line:
                    current_text.append(line)

        if current_section:
            sections[current_section] = " ".join(current_text).strip()

        return {"error": None, "sections": sections, "raw": content}

    except Exception as e:
        return {"error": f"⚠️ Groq API Error: {str(e)}"}


# ══════════════════════════════════════════════════════════════════════════
#  GENERATE PDF REPORT
# ══════════════════════════════════════════════════════════════════════════

def generate_pdf_report(
    result      : dict,
    stock_label : str,
    sentiment   : dict = None
) -> bytes:
    """
    Generate a professional PDF trading report.
    Returns PDF as bytes for download.
    """

    # ── Get AI Content ────────────────────────────────────────────
    report_data = generate_report_content(result, stock_label, sentiment)

    if report_data.get("error"):
        return None

    sections = report_data.get("sections", {})

    # ── PDF Setup ─────────────────────────────────────────────────
    buffer = io.BytesIO()
    doc    = SimpleDocTemplate(
        buffer,
        pagesize     = A4,
        rightMargin  = 0.75 * inch,
        leftMargin   = 0.75 * inch,
        topMargin    = 0.75 * inch,
        bottomMargin = 0.75 * inch
    )

    # ── Colors ────────────────────────────────────────────────────
    DARK_BG    = colors.HexColor("#0e1117")
    ACCENT     = colors.HexColor("#3498db")
    GREEN      = colors.HexColor("#26a69a")
    RED        = colors.HexColor("#ef5350")
    LIGHT_GRAY = colors.HexColor("#8b949e")
    WHITE      = colors.white
    DARK_CARD  = colors.HexColor("#1c2128")

    # ── Styles ────────────────────────────────────────────────────
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "Title",
        parent    = styles["Normal"],
        fontSize  = 24,
        textColor = WHITE,
        alignment = TA_CENTER,
        fontName  = "Helvetica-Bold",
        spaceAfter = 6
    )

    subtitle_style = ParagraphStyle(
        "Subtitle",
        parent    = styles["Normal"],
        fontSize  = 11,
        textColor = LIGHT_GRAY,
        alignment = TA_CENTER,
        fontName  = "Helvetica",
        spaceAfter = 4
    )

    section_heading_style = ParagraphStyle(
        "SectionHeading",
        parent     = styles["Normal"],
        fontSize   = 13,
        textColor  = ACCENT,
        fontName   = "Helvetica-Bold",
        spaceBefore = 16,
        spaceAfter  = 6
    )

    body_style = ParagraphStyle(
        "Body",
        parent    = styles["Normal"],
        fontSize  = 10,
        textColor = WHITE,
        fontName  = "Helvetica",
        leading   = 16,
        spaceAfter = 8
    )

    disclaimer_style = ParagraphStyle(
        "Disclaimer",
        parent    = styles["Normal"],
        fontSize  = 8,
        textColor = LIGHT_GRAY,
        fontName  = "Helvetica-Oblique",
        alignment = TA_CENTER,
        spaceAfter = 4
    )

    # ── Build PDF Elements ────────────────────────────────────────
    elements = []

    # ── Header ────────────────────────────────────────────────────
    elements.append(Spacer(1, 0.2 * inch))
    elements.append(Paragraph("🤖 AI Trading Assistant", title_style))
    elements.append(Paragraph("Stock Analysis Report — Simulation Only", subtitle_style))
    elements.append(Paragraph(
        f"Generated: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}",
        subtitle_style
    ))
    elements.append(Spacer(1, 0.2 * inch))
    elements.append(HRFlowable(
        width="100%", thickness=2,
        color=ACCENT, spaceAfter=12
    ))

    # ── Stock Summary Table ───────────────────────────────────────
    is_bullish     = result.get("signal", 0) == 1
    signal_color   = GREEN if is_bullish else RED
    signal_text    = result.get("prediction", "N/A")

    summary_data = [
        ["Stock", "Prediction", "Confidence", "Accuracy", "Close Price"],
        [
            stock_label,
            signal_text,
            f"{result.get('confidence', 0)}%",
            f"{result.get('accuracy', 0)}%",
            f"${result.get('latest_close', 0)}"
        ]
    ]

    summary_table = Table(summary_data, colWidths=[1.4*inch]*5)
    summary_table.setStyle(TableStyle([
        ("BACKGROUND",  (0, 0), (-1, 0),  ACCENT),
        ("BACKGROUND",  (0, 1), (-1, 1),  DARK_CARD),
        ("TEXTCOLOR",   (0, 0), (-1, 0),  WHITE),
        ("TEXTCOLOR",   (0, 1), (-1, 1),  WHITE),
        ("TEXTCOLOR",   (1, 1), (1, 1),   signal_color),
        ("FONTNAME",    (0, 0), (-1, 0),  "Helvetica-Bold"),
        ("FONTNAME",    (0, 1), (-1, 1),  "Helvetica"),
        ("FONTSIZE",    (0, 0), (-1, -1), 10),
        ("ALIGN",       (0, 0), (-1, -1), "CENTER"),
        ("VALIGN",      (0, 0), (-1, -1), "MIDDLE"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [DARK_CARD]),
        ("GRID",        (0, 0), (-1, -1), 0.5, ACCENT),
        ("TOPPADDING",  (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING",(0, 0), (-1, -1), 8),
        ("ROUNDEDCORNERS", [4]),
    ]))

    elements.append(summary_table)
    elements.append(Spacer(1, 0.15 * inch))

    # ── Technical Indicators Table ────────────────────────────────
    rsi        = result.get('latest_rsi', 0)
    rsi_status = (
        "Overbought" if rsi > 70
        else "Oversold" if rsi < 30
        else "Neutral"
    )
    ma_signal  = "Bullish ↑" if result.get('latest_ma7', 0) > result.get('latest_ma21', 0) else "Bearish ↓"

    indicators_data = [
        ["Indicator", "Value",    "Signal"],
        ["RSI (14)",  f"{rsi}",   rsi_status],
        ["MACD",      f"{result.get('latest_macd', 0)}", "Bullish" if result.get('latest_macd', 0) > 0 else "Bearish"],
        ["MA 7",      f"${result.get('latest_ma7', 0)}", ma_signal],
        ["MA 21",     f"${result.get('latest_ma21', 0)}", ma_signal],
    ]

    ind_table = Table(indicators_data, colWidths=[2.3*inch, 2.3*inch, 2.3*inch])
    ind_table.setStyle(TableStyle([
        ("BACKGROUND",  (0, 0), (-1, 0),  ACCENT),
        ("BACKGROUND",  (0, 1), (-1, -1), DARK_CARD),
        ("TEXTCOLOR",   (0, 0), (-1, 0),  WHITE),
        ("TEXTCOLOR",   (0, 1), (-1, -1), WHITE),
        ("FONTNAME",    (0, 0), (-1, 0),  "Helvetica-Bold"),
        ("FONTSIZE",    (0, 0), (-1, -1), 10),
        ("ALIGN",       (0, 0), (-1, -1), "CENTER"),
        ("VALIGN",      (0, 0), (-1, -1), "MIDDLE"),
        ("GRID",        (0, 0), (-1, -1), 0.5, ACCENT),
        ("TOPPADDING",  (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING",(0,0), (-1, -1), 8),
        ("ROWBACKGROUNDS", (0,1), (-1,-1), [DARK_CARD, colors.HexColor("#161b22")]),
    ]))

    elements.append(Paragraph("📊 Technical Indicators", section_heading_style))
    elements.append(ind_table)

    # ── AI Generated Sections ─────────────────────────────────────
    section_map = {
        "EXECUTIVE_SUMMARY"    : "📌 Executive Summary",
        "TECHNICAL_ANALYSIS"   : "📈 Technical Analysis",
        "PREDICTION_ANALYSIS"  : "🎯 Prediction Analysis",
        "SENTIMENT_ANALYSIS"   : "📰 Sentiment Analysis",
        "RISK_ASSESSMENT"      : "⚠️ Risk Assessment",
        "TRADING_RECOMMENDATION": "💡 Trading Recommendation",
        "DISCLAIMER"           : "⚠️ Disclaimer",
    }

    for key, heading in section_map.items():
        content = sections.get(key, "")
        if content:
            elements.append(
                Paragraph(heading, section_heading_style)
            )
            elements.append(
                HRFlowable(
                    width="100%", thickness=0.5,
                    color=LIGHT_GRAY, spaceAfter=6
                )
            )
            elements.append(Paragraph(content, body_style))

    # ── Footer ────────────────────────────────────────────────────
    elements.append(Spacer(1, 0.3 * inch))
    elements.append(HRFlowable(
        width="100%", thickness=1,
        color=ACCENT, spaceAfter=8
    ))
    elements.append(Paragraph(
        "⚠️ This report is generated by AI for educational and simulation purposes only.",
        disclaimer_style
    ))
    elements.append(Paragraph(
        "Not financial advice. Always do your own research before making investment decisions.",
        disclaimer_style
    ))
    elements.append(Paragraph(
        "Built with ❤️ using Streamlit · scikit-learn · Plotly · Groq · LLaMA 3.3",
        disclaimer_style
    ))

    # ── Build PDF ─────────────────────────────────────────────────
    doc.build(elements)
    pdf_bytes = buffer.getvalue()
    buffer.close()

    return pdf_bytes